#!/usr/bin/env bash

set +x

ARG1=${1:-ez80-cpu-v1.7}
NAME="${ARG1%.pld}"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

mkdir -p ./bin


move_to_bin() {
  [ -f "${NAME}.txt" ] && mv ${NAME}.doc bin/${NAME}.txt
  [ -f "${NAME}.mx" ] && mv ${NAME}.mx bin/${NAME}.mx
  [ -f "${NAME}.fit" ] && mv ${NAME}.fit bin/${NAME}.fit
  [ -f "${NAME}.io" ] && mv ${NAME}.io bin/${NAME}.io
  [ -f "${NAME}.abs" ] && mv ${NAME}.abs bin/${NAME}.abs
  [ -f "${NAME}.pin" ] && mv ${NAME}.pin bin/${NAME}.pin
  [ -f "${NAME}.pla" ] && mv ${NAME}.pla bin/${NAME}.pla
  [ -f "${NAME}.sim" ] && mv ${NAME}.sim bin/${NAME}.sim
  [ -f "${NAME}.tt2" ] && mv ${NAME}.tt2 bin/${NAME}.tt2
  [ -f "${NAME}.tt3" ] && mv ${NAME}.tt3 bin/${NAME}.tt3
  [ -f "${NAME}.lst" ] && mv ${NAME}.lst bin/${NAME}.lst
  [ -f "${NAME}.jed" ] && mv ${NAME}.jed bin/${NAME}.jed
  [ -f "${NAME}.doc" ] && mv ${NAME}.doc bin/${NAME}.doc

  chown ${CHOWN} -R bin
}

trap move_to_bin EXIT

wine cupl.exe -a -l -m4 -e -x -f -ju ${WINCUPLPATH}\cupl.dl  $NAME 2>>./bin/wincuplerror.log

# Define ANSI color codes
RED='\033[0;31m'
NC='\033[0m' # No Color

# Extract the PartNo attribute from the PLD file
partno=$(grep -i 'PartNo' "${NAME}.pld" | awk '{print $2}')

# Determine the correct fitter based on the PartNo
case "$partno" in
  ATF1502*)
    fitter="find1502"
    ;;
  ATF1504*)
    fitter="find1504"
    ;;
  ATF1508*)
    fitter="find1508"
    ;;
  *)
    echo "Unknown PartNo: $partno"
    exit 1
    ;;
esac

if [ -f "${NAME}.jed" ]; then
# Removed the location entry - the TL866II Plus programmer seems to have loading file issue
  sed -i '/Location/d' ./${NAME}.jed
  mv ${NAME}.jed ./bin
  wine ${fitter} ${NAME}.tt2
else
  # Print text in red
  echo -e "${RED}"
  wine ${fitter} ${NAME}.tt2
  echo -e "${NC}"
  exit 1
fi
